### PR TITLE
Google autocomplete (address and places): country state improvement

### PR DESCRIPTION
**Pull request by gityopie**

### CODE REVIEW

**Comment by gityopie** [comment]
@BT-aestebanez again, thanks for your review :)
I have pushed some commits, the changes is quite a lot than you are suggested
I'm improving some parts by removing useless code.

regarding the state, I modified the domain used to find ID of state on the backend https://github.com/gityopie/odoo-addons/pull/113/files#diff-b9375b49e00e98aa468e2cb7b374a9b9R74
changing the operator `=` by `ilike` and used the `long_name` of a state returning by Google.
on my several test, there are some address where the state is missing
for example this, (this is a random address):
 _Asse Mediano di Scorrimento, Cagliari, Province of Cagliari, Italy_
in Odoo the result looks like this:
Screen Shot 2019-09-16 at 23 51 54
compare to google autocomplete form (https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete-addressform)
Screen Shot 2019-09-16 at 23 52 12

the improvement will fix this

**Comment by BT-aestebanez** [comment]
Hi @gityopie 
I have tested it and the state is not filled due to the translations of the long name.
You can use for example: Spalentorweg, Basel, Switzerland
Thanks for your work,
Alvaro

**Comment by gityopie** [comment]
hi @BT-aestebanez,

yes, you're right about the translation.
I've reverted the modification I made for state.

let me know if this is ok
thanks

**Comment by BT-aestebanez** [comment]
Hi @gityopie 

Now it works properly
Thanks :+1:

**Pull request merged**
